### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by xlar54** [StewBC/cc65-Chess#9]
I get the following:  

mkdir -p obj/c64.chr
cl65 -t c64 -c --create-dep obj/c64.chr/undo.d  -o obj/c64.chr/undo.o src/undo.c
cl65 -t c64 -c --create-dep obj/c64.chr/frontend.d  -o obj/c64.chr/frontend.o src/frontend.c
cl65 -t c64 -c --create-dep obj/c64.chr/human.d  -o obj/c64.chr/human.o src/human.c
cl65 -t c64 -c --create-dep obj/c64.chr/globals.d  -o obj/c64.chr/globals.o src/globals.c
cl65 -t c64 -c --create-dep obj/c64.chr/cpu.d  -o obj/c64.chr/cpu.o src/cpu.c
cl65 -t c64 -c --create-dep obj/c64.chr/board.d  -o obj/c64.chr/board.o src/board.c
cl65 -t c64 -c --create-dep obj/c64.chr/main.d  -o obj/c64.chr/main.o src/main.c
cl65 -t c64 -c --create-dep obj/c64.chr/platC64CHR.d  -o obj/c64.chr/platC64CHR.o src/c64.chr/platC64CHR.c
cl65 -t c64 -c --create-dep obj/c64.chr/dataC64CHR.d  -o obj/c64.chr/dataC64CHR.o src/c64.chr/dataC64CHR.c
cl65 -t c64  -o cc65-Chess.c64.chr -C src/c64.chr/chessC64CHR.cfg obj/c64.chr/undo.o obj/c64.chr/frontend.o obj/c64.chr/human.o obj/c64.chr/globals.o obj/c64.chr/cpu.o obj/c64.chr/board.o obj/c64.chr/main.o obj/c64.chr/platC64CHR.o obj/c64.chr/dataC64CHR.o
ld65: Warning: src/c64.chr/chessC64CHR.cfg(11): Segment 'DATA' overflows memory area 'MAIN' by 107 bytes
ld65: Error: Cannot generate most of the files due to memory area overflow
make: *** [Makefile:310: cc65-Chess.c64.chr] Error 1

**Comment by StewBC** [comment]
Hi,

Make sure you compile with the optimise for size option, in other words:
make OPTIONS=optsize


On some systems make OPTIONS=optspeed will also work, but optsize is safe.

All the best,
Stefan
On 8/28/2020 8:56:55 AM, Scott Hutter <notifications@github.com> wrote:
I get the following:
mkdir -p obj/c64.chr
cl65 -t c64 -c --create-dep obj/c64.chr/undo.d -o obj/c64.chr/undo.o src/undo.c
cl65 -t c64 -c --create-dep obj/c64.chr/frontend.d -o obj/c64.chr/frontend.o src/frontend.c
cl65 -t c64 -c --create-dep obj/c64.chr/human.d -o obj/c64.chr/human.o src/human.c
cl65 -t c64 -c --create-dep obj/c64.chr/globals.d -o obj/c64.chr/globals.o src/globals.c
cl65 -t c64 -c --create-dep obj/c64.chr/cpu.d -o obj/c64.chr/cpu.o src/cpu.c
cl65 -t c64 -c --create-dep obj/c64.chr/board.d -o obj/c64.chr/board.o src/board.c
cl65 -t c64 -c --create-dep obj/c64.chr/main.d -o obj/c64.chr/main.o src/main.c
cl65 -t c64 -c --create-dep obj/c64.chr/platC64CHR.d -o obj/c64.chr/platC64CHR.o src/c64.chr/platC64CHR.c
cl65 -t c64 -c --create-dep obj/c64.chr/dataC64CHR.d -o obj/c64.chr/dataC64CHR.o src/c64.chr/dataC64CHR.c
cl65 -t c64 -o cc65-Chess.c64.chr -C src/c64.chr/chessC64CHR.cfg obj/c64.chr/undo.o obj/c64.chr/frontend.o obj/c64.chr/human.o obj/c64.chr/globals.o obj/c64.chr/cpu.o obj/c64.chr/board.o obj/c64.chr/main.o obj/c64.chr/platC64CHR.o obj/c64.chr/dataC64CHR.o
ld65: Warning: src/c64.chr/chessC64CHR.cfg(11): Segment 'DATA' overflows memory area 'MAIN' by 107 bytes
ld65: Error: Cannot generate most of the files due to memory area overflow
make: *** [Makefile:310: cc65-Chess.c64.chr] Error 1

**Comment by xlar54** [comment]
got it working.  thank you!
